# Generated by Django 4.2.7 on 2023-11-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=158)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField()),
                ('Team', models.CharField(max_length=100)),
                ('_2022', models.FloatField()),
                ('Last_3', models.FloatField()),
                ('Last_1', models.FloatField()),
                ('Home', models.FloatField()),
                ('Away', models.FloatField()),
                ('_2021', models.FloatField()),
            ],
        ),
    ]
