# Generated by Django 4.2.7 on 2023-11-06 15:20

from django.db import migrations, models
import django.db.models.deletion
import stats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=158)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('year_2022', models.CharField(blank=True, max_length=10, null=True)),
                ('last_3', models.CharField(blank=True, max_length=10, null=True)),
                ('last_1', models.CharField(blank=True, max_length=10, null=True)),
                ('home', models.CharField(blank=True, max_length=10, null=True)),
                ('away', models.CharField(blank=True, max_length=10, null=True)),
                ('year_2021', models.CharField(blank=True, max_length=10, null=True)),
                ('original_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stats_details_formatted_html', models.TextField(blank=True, null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='ResultAndScheduleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, validators=[stats.models.validate_mmdd_date_format])),
                ('opponent', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('win_loss', models.CharField(blank=True, max_length=1, null=True)),
                ('conference', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_and_schedule_stats', to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='PowerRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predictive_rating', models.CharField(blank=True, help_text='Predictive Power Rating', max_length=50, null=True)),
                ('home_rating', models.CharField(blank=True, help_text='Home Power Rating', max_length=50, null=True)),
                ('away_rating', models.CharField(blank=True, help_text='Away Power Rating', max_length=50, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_ratings', to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='KeyOffensiveStatsLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points_per_game', models.CharField(blank=True, help_text='Points Per Game', max_length=50, null=True)),
                ('average_score_margin', models.CharField(blank=True, help_text='Average Score Margin', max_length=50, null=True)),
                ('assists_per_game', models.CharField(blank=True, help_text='Assists Per Game', max_length=50, null=True)),
                ('total_rebounds_per_game', models.CharField(blank=True, help_text='Total Rebounds Per Game', max_length=50, null=True)),
                ('effective_fg_percentage', models.CharField(blank=True, help_text='Effective FG Percentage', max_length=50, null=True)),
                ('offensive_rebound_percentage', models.CharField(blank=True, help_text='Offensive Rebound Percentage', max_length=50, null=True)),
                ('free_throw_attempt_to_field_goal_attempt_ratio', models.CharField(blank=True, help_text='Free Throw Attempt to Field Goal Attempt Ratio', max_length=50, null=True)),
                ('turnover_percentage', models.CharField(blank=True, help_text='Turnover Percentage', max_length=50, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_offensive_stats', to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='KeyDefensiveStatsLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opponent_points_per_game', models.CharField(blank=True, help_text='Opponent Points Per Game', max_length=50, null=True)),
                ('opponent_effective_fg_percentage', models.CharField(blank=True, help_text='Opponent Effective FG Percentage', max_length=50, null=True)),
                ('offensive_rebounds_per_game', models.CharField(blank=True, help_text='Offensive Rebounds Per Game', max_length=50, null=True)),
                ('defensive_rebounds_per_game', models.CharField(blank=True, help_text='Defensive Rebounds Per Game', max_length=50, null=True)),
                ('blocks_per_game', models.CharField(blank=True, help_text='Blocks Per Game', max_length=50, null=True)),
                ('steals_per_game', models.CharField(blank=True, help_text='Steals Per Game', max_length=50, null=True)),
                ('personal_fouls_per_game', models.CharField(blank=True, help_text='Personal Fouls Per Game', max_length=50, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_defensive_stats', to='stats.team')),
            ],
        ),
    ]
