# Generated by Django 4.2.7 on 2023-11-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultandschedulestats',
            name='money',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resultandschedulestats',
            name='spread',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resultandschedulestats',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultandschedulestats',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
