# Generated by Django 4.2.7 on 2023-11-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Away',
            new_name='away',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Home',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Last_1',
            new_name='last_1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Last_3',
            new_name='last_3',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Rank',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='_2021',
            new_name='year_2021',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='_2022',
            new_name='year_2022',
        ),
    ]
