# Generated by Django 4.2.7 on 2023-11-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_away_team_away_rename_home_team_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='away',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='home',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='year_2021',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='year_2022',
            field=models.CharField(max_length=10),
        ),
    ]
