# Generated by Django 4.2.7 on 2023-11-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_team_away_alter_team_home_alter_team_last_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predictive_rating', models.CharField(blank=True, help_text='Predictive Power Rating', max_length=50, null=True)),
                ('home_rating', models.CharField(blank=True, help_text='Home Power Rating', max_length=50, null=True)),
                ('away_rating', models.CharField(blank=True, help_text='Away Power Rating', max_length=50, null=True)),
                ('points_per_game', models.CharField(blank=True, help_text='Points Per Game', max_length=50, null=True)),
                ('average_score_margin', models.CharField(blank=True, help_text='Average Score Margin', max_length=50, null=True)),
                ('assists_per_game', models.CharField(blank=True, help_text='Assists Per Game', max_length=50, null=True)),
                ('total_rebounds_per_game', models.CharField(blank=True, help_text='Total Rebounds Per Game', max_length=50, null=True)),
                ('effective_fg_percentage', models.CharField(blank=True, help_text='Effective FG Percentage', max_length=50, null=True)),
                ('offensive_rebound_percentage', models.CharField(blank=True, help_text='Offensive Rebound Percentage', max_length=50, null=True)),
                ('free_throw_attempt_to_field_goal_attempt_ratio', models.CharField(blank=True, help_text='Free Throw Attempt to Field Goal Attempt Ratio', max_length=50, null=True)),
                ('turnover_percentage', models.CharField(blank=True, help_text='Turnover Percentage', max_length=50, null=True)),
                ('opponent_points_per_game', models.CharField(blank=True, help_text='Opponent Points Per Game', max_length=50, null=True)),
                ('opponent_effective_fg_percentage', models.CharField(blank=True, help_text='Opponent Effective FG Percentage', max_length=50, null=True)),
                ('offensive_rebounds_per_game', models.CharField(blank=True, help_text='Offensive Rebounds Per Game', max_length=50, null=True)),
                ('defensive_rebounds_per_game', models.CharField(blank=True, help_text='Defensive Rebounds Per Game', max_length=50, null=True)),
                ('blocks_per_game', models.CharField(blank=True, help_text='Blocks Per Game', max_length=50, null=True)),
                ('steals_per_game', models.CharField(blank=True, help_text='Steals Per Game', max_length=50, null=True)),
                ('personal_fouls_per_game', models.CharField(blank=True, help_text='Personal Fouls Per Game', max_length=50, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.team')),
            ],
        ),
    ]
