# Generated by Django 4.2.7 on 2023-11-02 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_team_slug_teamstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='stats.team'),
        ),
    ]
